## Numpy Daily Practice 1

1. Import the numpy package under the name np (★☆☆)
 
2. Print the numpy version and the configuration (★☆☆)
 
3. Create a null vector of size 10 (★☆☆)
 
4. How to find the memory size of any array (★☆☆)
 
5. How to get the documentation of the numpy add function from the command line? (★☆☆)
 
6. Create a null vector of size 10 but the fifth value which is 1.

7. Create a vector with values ranging from 10 to 49 (★☆☆)
 
8. Reverse a vector (first element becomes last) (★☆☆)
 
9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
 
10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
 
11. Create a 3x3 identity matrix (★☆☆)

12. Create a 3x3x3 array with random values (★☆☆)
 
13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
 
14. Create a random vector of size 30 and find the mean value (★☆☆)
 
15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
 

In [5]:
# 1.Import the numpy package under the name np (★☆☆)


import numpy as np

In [6]:
#2. Print the numpy version and the configuration (★☆☆)
 


np.__version__

'2.0.0'

In [7]:
#3. Create a null vector of size 10 (★☆☆)
 


null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
#4.How to find the memory size of any array (★☆☆)
 
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


In [9]:
#5.How to get the documentation of the numpy add function from the command line? (★☆☆)
 

help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its or

In [10]:
#6. Create a null vector of siHze 10 but the fifth value which is 1.


null_vector=np.zeros(10)

null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [11]:
##7. Create a vector with values ranging from 10 to 49 (★☆☆)
 

vector1 = np.random.randint(10,49,10)
print(vector1)

[29 16 46 11 16 34 18 34 23 33]


In [12]:
#8. Reverse a vector (first element becomes last) (★☆☆)

reversedVector= vector1[::-1]
print(reversedVector)


[33 23 34 18 34 16 11 46 16 29]


In [13]:
#9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
 
arr1 = np.random.randint(0,8,(3,3))
print(arr1)

[[5 6 5]
 [2 7 2]
 [2 1 3]]


In [14]:
#10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
 
arry = np.array([1,2,0,0,4,0])

non_zero = np.nonzero(arry)[0]
print(non_zero)


[0 1 4]


In [15]:
#11. Create a 3x3 identity matrix (★☆☆)

identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
#12. Create a 3x3x3 array with random values (★☆☆)
 
arr2 = np.random.random((3,3))
print(arr2)

[[0.66914189 0.10063397 0.93184528]
 [0.26694009 0.42505406 0.67591133]
 [0.12562557 0.20337136 0.36131597]]


In [17]:
#13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
 
arr3 = np.random.random((10,10))
print(f'array: {arr3}')
max_value = np.max(arr3)
print(f'maximum : {max_value}')
min_value = np.min(arr3)
print(f'minimum:{min_value}')


array: [[0.04295669 0.39917047 0.97919137 0.76128    0.46607761 0.71370259
  0.34626044 0.41753923 0.41761658 0.22274138]
 [0.25173274 0.06673778 0.59254986 0.61370954 0.6990441  0.41853858
  0.53009436 0.45594875 0.62347967 0.20642593]
 [0.22660002 0.87167091 0.80100293 0.83264765 0.90653173 0.11895111
  0.49124169 0.42547496 0.86519607 0.29497437]
 [0.46198706 0.41445652 0.0686     0.12230048 0.97106898 0.77392417
  0.46357615 0.1511261  0.70156049 0.98882598]
 [0.33793774 0.42724402 0.94434834 0.02450983 0.76976866 0.37382576
  0.13778785 0.57945007 0.59276506 0.94664185]
 [0.97871543 0.94400697 0.43593498 0.29396379 0.45690892 0.5650944
  0.62899982 0.26579186 0.31235973 0.04643521]
 [0.5300518  0.55718252 0.5191893  0.16204605 0.38314608 0.44950395
  0.9518892  0.12213556 0.60531656 0.7527475 ]
 [0.41820271 0.95989334 0.95455378 0.75895834 0.56275034 0.49566883
  0.88420575 0.13362173 0.26988356 0.25900614]
 [0.37113019 0.7141728  0.94606132 0.10935008 0.52941588 0.7724833
  0.288

In [18]:
#14. Create a random vector of size 30 and find the mean value (★☆☆)
 
randomVector = np.random.random(30)
print(randomVector)
mean_vector = np.mean(randomVector)
print(mean_vector)

[0.71047488 0.6826857  0.87418326 0.74174321 0.12383981 0.67032768
 0.86043134 0.62611907 0.69759205 0.39510354 0.43327371 0.21742663
 0.74695709 0.46009807 0.18772902 0.19457328 0.95175738 0.53319218
 0.65278064 0.42238134 0.7792196  0.02217807 0.51607348 0.39437895
 0.64340678 0.03221276 0.37720263 0.45290734 0.43519039 0.31522673]
0.5050222205657429


In [19]:
#15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

arr4 = np.zeros((5,5))
print(f'original array: {arr4}')

arr4[0,: ] = 1
arr4[:, 0] = 1
arr4[-1, :] = 1
arr4[:, -1] = 1

print(f'new array: {arr4}')

original array: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
new array: [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Numpy Daily Prcatice 2

16. How to add a border (filled with 0's) around an existing array? (★☆☆)
 
17. What is the result of the following expression? (★☆☆)
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
 
18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
 
19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
 
21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
 
22. Normalize a 5x5 random matrix (★☆☆)
 
23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
 
24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
 
25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
 
26. What is the output of the following script? (★☆☆)

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
 
28. What are the result of the following expressions?
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
 
29. How to round away from zero a float array ? (★☆☆)
 
30. How to find common values between two arrays? (★☆☆)



In [20]:
# 16

arr1 = np.ones((3,3))

padded_arr1 = np.pad(arr1,pad_width=1,mode='constant', constant_values= 0)

print(padded_arr1)


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
#17. What is the result of the following expression? (★☆☆)
result1 = 0 * np.nan
print(f'result1 : {result1}')

result2 = np.nan == np.nan
print(f'Result2 : {result2}')

result3 = np.inf > np.nan
print(f'result3: {result3}')

result4 = np.nan - np.nan
print(f'result4: {result4}')

result5 = np.nan in set([np.nan])
print(f'result5: {result5}')

result6 = 3 == 3 * 0.1
print(f'result6: {result6}')

result1 : nan
Result2 : False
result3: False
result4: nan
result5: True
result6: True


In [22]:
#18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

values = np.array([1,2,3,4])

matrix = np.zeros((5,5))

matrix =+ np.diag(values,k=-1)

print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [11]:
# 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

matrix = np.zeros((8,8))

matrix[1::2,::2] = 1
matrix[::2,1::2] = 1

print(matrix)



[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [24]:
#20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

shape = (6,7,8)

index1 = 99

multiIndex = np.unravel_index(index1,shape)

print(multiIndex)

(np.int64(1), np.int64(5), np.int64(3))


In [12]:
#21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

a = np.array([[1,0],[0,1]])

matrix = np.tile(a,(4,4))
print(matrix)

print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
[[1 0]
 [0 1]]


In [14]:
#21.Normalize a 5x5 random matrix (★☆☆)

#Min - Max Normalization

random_matrix = np.random.random((5,5))

min_value = np.min(random_matrix)
max_value = np.max(random_matrix)

normalized_matrix = (random_matrix - min_value) / (max_value - min_value)

print(f'OriginalMatrix:\n {random_matrix}')
print(f'NormalizedMatrix:\n {normalized_matrix}')

OriginalMatrix:
 [[0.80051711 0.54679354 0.4441171  0.95330842 0.1264255 ]
 [0.08182886 0.14446994 0.0407995  0.1764425  0.67282   ]
 [0.15728871 0.20654481 0.97821134 0.73529773 0.19853595]
 [0.83543891 0.65015323 0.63727584 0.175103   0.52784443]
 [0.19164062 0.10358452 0.61213554 0.81483345 0.64918252]]
NormalizedMatrix:
 [[0.81044166 0.53977774 0.4302459  0.97343439 0.09134299]
 [0.04376877 0.11059221 0.         0.14469948 0.6742186 ]
 [0.12426685 0.17681163 1.         0.74086778 0.16826804]
 [0.84769508 0.65003844 0.63630126 0.14327055 0.51956345]
 [0.16091233 0.066977   0.60948242 0.82571386 0.64900292]]


In [15]:
#Normalization by Z Score method
Z = np.mean(random_matrix)


result = random_matrix - Z / np.std(random_matrix)
print(result)

[[-0.72112804 -0.97485161 -1.07752805 -0.56833673 -1.39521965]
 [-1.43981629 -1.37717521 -1.48084565 -1.34520265 -0.84882515]
 [-1.36435644 -1.31510034 -0.54343381 -0.78634743 -1.32310921]
 [-0.68620624 -0.87149192 -0.88436931 -1.34654215 -0.99380072]
 [-1.33000453 -1.41806063 -0.90950961 -0.7068117  -0.87246263]]


In [19]:
#23.Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

colorDtype=np.dtype([('R',np.ubyte),('G',np.ubyte),('B',np.ubyte),('A',np.ubyte)])

colors = np.array([(255,0,0,255),
                   (0,255,0,255),
                   (0,0,255,255),
                   (255,255,0,255)],dtype=colorDtype)

print(colors)
print(colors.dtype)


[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)
 (255, 255,   0, 255)]
[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


In [23]:
#24.Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

matrix1 = np.random.randint(1,30,(5,3))
matrix2 = np.random.randint(30,60,(3,2))

#result = matrix1*matrix2
result1 = np.dot(matrix1,matrix2)

print(f'{matrix1}\n multiply \n{matrix2}\n is\n{result1}')


[[14  9 25]
 [27 11 28]
 [22 26  5]
 [14 26  2]
 [24 29 12]]
 multiply 
[[32 34]
 [57 52]
 [39 59]]
 is
[[1936 2419]
 [2583 3142]
 [2381 2395]
 [2008 1946]
 [2889 3032]]


In [25]:
A = np.array([1,2,3])
B = np.array([4,5])

result = np.dot(A,B)

print(result)

ValueError: shapes (3,) and (2,) not aligned: 3 (dim 0) != 2 (dim 0)

In [26]:
matrix1

array([[14,  9, 25],
       [27, 11, 28],
       [22, 26,  5],
       [14, 26,  2],
       [24, 29, 12]], dtype=int32)

In [27]:
matrix2

array([[32, 34],
       [57, 52],
       [39, 59]], dtype=int32)

In [29]:
#25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

arr =np.array([1,2,3,4,5,6,7,8])

arr[(3<arr)&(arr<8)] *= -1

print(arr)

[ 1  2  3 -4 -5 -6 -7  8]


In [30]:
#26. What is the output of the following script? (★☆☆)

print(sum(range(5),-1)) #python method
from numpy import *
print(sum(range(5),-1)) #numpy method

print(range(5))

9
10
range(0, 5)


In [31]:
np.sum?

Signature:      
np.sum(
    a,
    axis=None,
    dtype=None,
    out=None,
    keepdims=<no value>,
    initial=<no value>,
    where=<no value>,
)
Call signature:  np.sum(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function sum at 0x00000173105DDDA0>
File:            c:\users\kathleen\desktop\datavisualization\datavis\lib\site-packages\numpy\_core\fromnumeric.py
Docstring:      
Sum of array elements over a given axis.

Parameters
----------
a : array_like
    Elements to sum.
axis : None or int or tuple of ints, optional
    Axis or axes along which a sum is performed.  The default,
    axis=None, will sum all of the elements of the input array.  If
    axis is negative it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a sum is performed on all of the axes
    specified in the tuple instead of a single axis or all the axes as
    before.
dtype : dtype, optional
    The type of the returned array

In [ ]:
#27.Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z = np.array([1,2,3,4,5,6,7,8])
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

In [ ]:
#28. What are the result of the following expressions?

result7 = np.array(0) / np.array(0)
print(f'result7: {result7}')

result8 = np.array(0) // np.array(0)
print(f'result8: {result8}')

result9 = np.array([np.nan]).astype(int).astype(float)
print(f'result9: {result9}')

result7: nan
result8: 0
result9: [-9.22337204e+18]


C:\Users\Kathleen\AppData\Local\Temp\ipykernel_12644\985100537.py:3: RuntimeWarning: invalid value encountered in divide
  result7 = np.array(0) / np.array(0)
C:\Users\Kathleen\AppData\Local\Temp\ipykernel_12644\985100537.py:6: RuntimeWarning: divide by zero encountered in floor_divide
  result8 = np.array(0) // np.array(0)
C:\Users\Kathleen\AppData\Local\Temp\ipykernel_12644\985100537.py:9: RuntimeWarning: invalid value encountered in cast
  result9 = np.array([np.nan]).astype(int).astype(float)


In [35]:

14//5

2

In [36]:
#29. How to round away from zero a float array ? (★☆☆)

import numpy as np

float_arr = np.array([1.7,1.3,0.2,-0.5,-1.7])

rounded_arr = np.ceil(float_arr)
rounded_to = np.floor(float_arr)

print('Original array:\n',float_arr)
print('Rounded array:\n',rounded_arr)
print(rounded_to)



Original array:
 [ 1.7  1.3  0.2 -0.5 -1.7]
Rounded array:
 [ 2.  2.  1. -0. -1.]
[ 1.  1.  0. -1. -2.]


In [3]:
#30. How to find common values between two arrays? 

arr1 = np.array([1,3,5,7,9])
arr2 = np.array([8,7,5,4,2])

common = np.intersect1d(arr1,arr2)

print('common values:',common)

common values: [5 7]


## Numpy Daily Practice 3

31. How to ignore all numpy warnings (not recommended)? (★☆☆)
 
32. Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)
 
33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
 
34. How to get all the dates corresponding to the month of July 2016? (★★☆)

35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
 
36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
 
37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
 
38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
 
40. Create a random vector of size 10 and sort it (★★☆)
 
41. How to sum a small array faster than np.sum? (★★☆)
 
42. Consider two random array A and B, check if they are equal (★★☆)

43. Make an array immutable (read-only) (★★☆)
 
44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
 
45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

 


In [ ]:
#31. How to ignore all numpy warnings (not recommended)? (★☆☆)
 
np.seterr(all = 'ignore')



In [ ]:
#32. Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)
 


C:\Users\Kathleen\AppData\Local\Temp\ipykernel_13916\2433753584.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

In [ ]:
#33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

today = np.datetime64('today','D')
yesterday = today - np.timedelta64(1,'D')
tomorrow = today + np.timedelta64(1, 'D')

print('Yesterday:',yesterday)
print('Today:',today)
print('Tomorrow:',tomorrow)

Yesterday: 2024-07-08
Today: 2024-07-09
Tomorrow: 2024-07-10


In [ ]:
#34. How to get all the dates corresponding to the month of July 2016? (★★☆)

july_2016 = np.arange('2016-07-01','2016-08-01',dtype='datetime64[D]')
print(july_2016)


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [ ]:
#35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

a = np.arange(5)
b = np.arange(5)

np.add(a,b,out=b)
np.negative(a,out=a)
np.divide(a,2,out=a)
np.multiply(a,b,out=b)


In [ ]:
#36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

arr = np.random.uniform(0,10,(5,5))
print(f'Original array:\n',arr)

method1 = np.floor(arr)
method2 = np.ceil(arr)
method3 = np.trunc(arr)

print('floor method: \n ',method1)
print('ceiling method: \n', method2)
print('truncating method: \n',method3)


Original array:
 [[5.28217145 6.93536594 6.14488842 6.84495904 8.96306329]
 [8.80785018 2.35711516 0.59433184 3.6430693  0.920661  ]
 [7.93429463 9.73171271 7.43044766 8.1583902  4.00523385]
 [5.24032671 8.90657735 2.29814338 6.95992424 0.55345583]
 [1.47750961 6.45101121 5.16819247 1.58313588 3.48401655]]
floor method: 
  [[5. 6. 6. 6. 8.]
 [8. 2. 0. 3. 0.]
 [7. 9. 7. 8. 4.]
 [5. 8. 2. 6. 0.]
 [1. 6. 5. 1. 3.]]
ceiling method: 
 [[ 6.  7.  7.  7.  9.]
 [ 9.  3.  1.  4.  1.]
 [ 8. 10.  8.  9.  5.]
 [ 6.  9.  3.  7.  1.]
 [ 2.  7.  6.  2.  4.]]
truncating method: 
 [[5. 6. 6. 6. 8.]
 [8. 2. 0. 3. 0.]
 [7. 9. 7. 8. 4.]
 [5. 8. 2. 6. 0.]
 [1. 6. 5. 1. 3.]]


In [ ]:
#37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
 

arr = np.arange(5)
arr2 = np.tile(arr,(5,1))
print('original array:', arr)
print('matrix: \n', arr2)

original array: [0 1 2 3 4]
matrix: 
 [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [37]:
#38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

def generate():
    array = np.random.randint(1,20,10)
    return array

print(generate())

[ 6 10 17  7 11  5  7  4  7 12]


In [38]:
#39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
 
arr = np.linspace(0,1,12,endpoint=True)
print(arr)
arr[1:-1]

arr = np,linspace(0,1,11,endpoint=False)[1:]
print(arr)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]
(<module 'numpy' from 'c:\\Users\\Kathleen\\Desktop\\datavisualization\\datavis\\Lib\\site-packages\\numpy\\__init__.py'>, array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091]))


In [ ]:
#40. Create a random vector of size 10 and sort it (★★☆)
 
arr = np.random.random(10)
sorted_arr =np.sort(arr)
print(sorted_arr)

[0.05207188 0.0662461  0.40015595 0.54338231 0.69741788 0.80981452
 0.87573071 0.88528566 0.93202179 0.98732838]


In [ ]:
#41. How to sum a small array faster than np.sum? (★★☆)
 
import time

arr = np.array([1,2,3,4,5])
#using np.sum
starttime= time.time()
output = np.sum(arr)
endtime = time.time()
tt = endtime - starttime
print(f'{output} : {tt}')

#using np.add.reduce
starttime = time.time()
output = np.add.reduce(arr)
endtime = time.time()
tt = endtime - starttime
print(f'{output} : {tt}')


15 : 0.0
15 : 0.0


In [ ]:
#42. Consider two random array A and B, check if they are equal (★★☆)
A = np.random.random(10)
B = np.random.random(10)

equal = np.array_equal(A,B)
print(equal)

False


In [ ]:
#43. Make an array immutable (read-only) (★★☆)
 
arr = np.zeros(10)
arr.flags.writeable = False
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [39]:
#44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
 
cartesian_plane = np.random.rand(10,2)

x = cartesian_plane[:,0]
y = cartesian_plane[:,1]

r = np.sqrt(x**2 + y**2)

theta = np.arctan2(y,x)

polar_coordinates = np.column_stack(r,theta)

print('Cartesian Coordinates:\n',cartesian_plane)
print('Polar Coordinates: \n', polar_coordinates)


TypeError: column_stack() takes 1 positional argument but 2 were given

In [42]:
#45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

arr = np.random.randint(1,10,10)
z = np.argmax(arr)
z = 0
print(arr)


[4 7 8 6 8 9 7 4 7 2]


61. Find the nearest value from a given value in an array (★★☆)
 
62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
 
63. Create an array class that has a name attribute (★★☆)
 
64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
 
66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)
 
67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
 
68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)
 
69. How to get the diagonal of a dot product? (★★★)

70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
 
71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)
 
72. How to swap two rows of an array? (★★★)
 
73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)
 
74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

75. How to compute averages using a sliding window over an array? (★★★)
 
76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
 
77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
 
78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)
79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)
 
80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)
 
81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
 
82. Compute a matrix rank (★★★)

83. How to find the most frequent value in an array?
 
84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
 
85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)
 
86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
 
87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

88. How to implement the Game of Life using numpy arrays? (★★★)
 
89. How to get the n largest values of an array (★★★)
 
90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)
 
91. How to create a record array from a regular array? (★★★)
 
92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
 
94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)
 
95. Convert a vector of ints into a matrix binary representation (★★★)
 
96. Given a two dimensional array, how to extract unique rows? (★★★)
 
97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
 
99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
 
100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
 

In [46]:
#61. Find the nearest value from a given value in an array (★★☆)
import numpy as np

arr = np.random.normal(5,10,(3,4))
print(arr)
value = 0.5
nearest_value = np.abs(arr-value).argmin()
print('nearest value:',nearest_value)

[[ 10.63013206   4.9568667   11.1746069  -12.83023641]
 [  5.59274379  -2.3906664   -8.90109288   9.09352374]
 [  6.07801752   6.51272656  13.45972935  -3.97707632]]
nearest value: 5


In [48]:
#62. Considering two arrays with shape (1,3) and (3,1), 
# how to compute their sum using an iterator? (★★☆)

arr1 = np.random.randint(10,50,size=(1,3))
arr2 = np.random.randint(10,50,size=(3,1))

iterator=np.nditer(arr1,arr2,None)

for a,b,c in iterator:
    c[...]=a+b

iterator.operands[2]




ValueError: Iterator global flags must be a list or tuple of strings

In [49]:
#63. Create an array class that has a name attribute (★★☆)



class Arr(np.ndarray):
    def __new__(cls,array,name='no name'):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def array_finalize(self,obj):
        if obj is None: return
        self.name = getattr(obj,'name','no name')


a = Arr(np.arange(10),'custom_array')
a.name

'custom_array'

In [ ]:
#64. Consider a given vector, 
# how to add 1 to each element indexed by a second vector (be careful with repeated indices)?
#  (★★★)

vector1 = np.array([1,2,3,4,5,6,7])
indices = np.array([0,1,1,2,2,3,3])

np.add.at(vector1,indices,1)

print(vector1)



[2 4 5 6 5 6 7]


In [ ]:
#65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

X = np.array([1,2,3,4,5,6])
I = np.array([1,2,2,3,3,4])
F= np.zeros(5)

np.add.at(F,I,X)

print(F)

[0. 1. 5. 9. 6.]


In [ ]:
#66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

w,h = (7,7)

image =np.random.randint(0,256,size=(w,h,3),dtype=np.uint8)
reshaped_image = np.reshape(image,(-1,3))
unique = np.unique(reshaped_image,axis=0)
unique_num = np.shape(unique)[0]

print(f'The number of unique numbers:',unique_num)



The number of unique numbers: 49


In [ ]:
w,h = 256,256
image =np.random.randint (0,4,(h,w,3)).astype(np.ubyte)

reshaped_image= image.reshape(-1,3)
len(np.unique(reshaped_image,axis =0))

In [ ]:
#67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

arr_4d = np.random.rand(2,3,4,5)

sum_of_arr_4d=np.sum(arr_4d,axis=(-2,-1))

print('array:\n' ,arr_4d)
print('sum \n',sum_of_arr_4d)


array:
 [[[[0.75644633 0.5351094  0.9544045  0.37980908 0.76364838]
   [0.19722623 0.28517139 0.82801435 0.89881302 0.78746703]
   [0.85615435 0.16780454 0.18974018 0.19706667 0.89331812]
   [0.05472552 0.61931769 0.08239199 0.48461316 0.26449928]]

  [[0.76662445 0.19732197 0.68882845 0.14661621 0.93245473]
   [0.36394818 0.23650763 0.54726623 0.04968114 0.20887283]
   [0.21055748 0.94915176 0.26959436 0.22591103 0.23465347]
   [0.67586275 0.25202246 0.97858724 0.57485148 0.34947894]]

  [[0.79560153 0.52103868 0.31983914 0.02140889 0.08534074]
   [0.00421086 0.46966471 0.27665504 0.4864604  0.81064817]
   [0.3642944  0.56968    0.19473318 0.10645251 0.22649505]
   [0.36853292 0.84557279 0.02424921 0.80655386 0.62779332]]]


 [[[0.56769202 0.81785268 0.95528696 0.31493455 0.84678839]
   [0.36850418 0.13344275 0.22374602 0.51789887 0.84009034]
   [0.45326015 0.64103128 0.31155683 0.17748171 0.53909435]
   [0.64082054 0.01304775 0.04210688 0.21675338 0.50794078]]

  [[0.15107993 0.39895

In [ ]:
#68. Considering a one-dimensional vector D, 
# how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)

import numpy as np

D = np.array([1,2,3,4,5,6,7])
S = np.array([1,0,1,0,1,0,1])

unique_indices = np.unique(S)

sums = np.zeros_like(unique_indices,dtype=np.float64)
counts = np.zeros_like(unique_indices,dtype=np.int32)

np.add.at(sums,S,D)
np.add.at(counts,S,1)

means = sums/counts

print(means)




[4. 4.]


In [ ]:
#69. How to get the diagonal of a dot product? (★★★)

a = [[1,0],[0,1]]
b = [[4,1],[2,2]]

arr = np.dot(a,b)

c = np.diag(arr)
print(c)

[4 2]


In [29]:
#70. Consider the vector [1, 2, 3, 4, 5],
#  how to build a new vector with 3 consecutive zeros 
# interleaved between each value? (★★★)

original_vector = np.array([1,2,3,4,5])

zeros = 3

new_length = len(original_vector) + zeros*(len(original_vector)-1)

new_vector = np.zeros(new_length,dtype=original_vector.dtype)

new_vector[::zeros+1] = original_vector

print(f'Original vector:',original_vector)
print('new vector:',new_vector)

Original vector: [1 2 3 4 5]
new vector: [1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


In [30]:
#71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

arr1 = np.random.random((5,5,3))
arr2 = np.random.random((5,5))

result = arr1*arr2[:,:,np.newaxis]

print('3D Array:\n',arr1)
print('2D Array:\n',arr2)
print('Multplication result:\n',result)

3D Array:
 [[[0.88601832 0.18426565 0.77518847]
  [0.01851257 0.83900043 0.28864764]
  [0.93921678 0.09225456 0.98165307]
  [0.00493151 0.91697318 0.19154075]
  [0.11280841 0.28009013 0.09177059]]

 [[0.49027762 0.78859545 0.98866539]
  [0.36597639 0.67016122 0.61483462]
  [0.81938408 0.81116455 0.89578011]
  [0.00560556 0.23155973 0.88363314]
  [0.22885918 0.75678651 0.0396149 ]]

 [[0.77956832 0.58431902 0.80015058]
  [0.79941852 0.00509555 0.56485105]
  [0.64647361 0.10783146 0.77395849]
  [0.84033889 0.33735016 0.93957607]
  [0.7574602  0.14397325 0.46426511]]

 [[0.14869849 0.44737425 0.0561803 ]
  [0.25953264 0.21534485 0.9653302 ]
  [0.63004118 0.33130794 0.60575428]
  [0.43609933 0.56128523 0.76385639]
  [0.02003993 0.63462477 0.00703516]]

 [[0.35109759 0.778888   0.98744671]
  [0.14743326 0.99514794 0.20870256]
  [0.45151337 0.99786708 0.84968354]
  [0.34663032 0.10608946 0.93732098]
  [0.8812091  0.42489746 0.61725831]]]
2D Array:
 [[0.32919927 0.93268593 0.87360037 0.357901

In [31]:
#72. How to swap two rows of an array? (★★★)
arrays = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(arrays)

arrays[[0,2]] = arrays[[2,0]]
print(arrays)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [ ]:
#73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)


In [33]:
#74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
arr1 = np.array([1,2,3,4,5])

arr2 = np.repeat(np.arange(len(arr1)),arr1)

print('Bincount array:\n',arr1)
print('Resultant array\n',arr2)
print('Bincount:\n',np.bincount(arr2))




Bincount array:
 [1 2 3 4 5]
Resultant array
 [0 1 1 2 2 2 3 3 3 3 4 4 4 4 4]
Bincount:
 [1 2 3 4 5]


In [34]:
#75. How to compute averages using a sliding window over an array? (★★★)

arr = np.array([1,2,3,4,5,6,7,8,9,10])
window_size = 3

def sliding_window_avg(array,window_size):
    window = np.ones(window_size)/window_size
    return np.convolve(array,window,mode='valid')

averages = sliding_window_avg(arr,window_size)
print(arr)
print(averages)

[ 1  2  3  4  5  6  7  8  9 10]
[2. 3. 4. 5. 6. 7. 8. 9.]


In [36]:
#76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

arr = np.array([1,2,3,4,5,6,7,8,9])

def build_shifted_array(arr,num_shifts):
    n = len(arr)
    return np.array([arr[i:i+num_shifts] for i in range(n - num_shifts +1)])

num_shifts = 3
shifted_arr = build_shifted_array(arr,num_shifts)

print('Original array:\n',arr)
print('Shifted array:\n',shifted_arr)


Original array:
 [1 2 3 4 5 6 7 8 9]
Shifted array:
 [[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [37]:
#77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

boolean_value = True
boolean_value = not boolean_value
print(boolean_value)

float_value = 3.14
float_value = -float_value
print(float_value)


False
-3.14


In [ ]:
#78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)


In [ ]:
#79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
#80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)

In [38]:
#81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,])

def generate_subarrays(Z,subarray_length):
    R=[Z[i:i+subarray_length] for i in range(len(Z) - subarray_length +1 )]
    return np.array(R)

subarray_length = 4
R = generate_subarrays(Z, subarray_length)

print('Arrray Z:\n' ,Z)
print('Array R:\n',R)

Arrray Z:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Array R:
 [[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [39]:
#82. Compute a matrix rank (★★★)

arr = np.arrays([[1,2,3],
                [4,5,6],
                [7,8,9]])

rank = np.linalg.matrix_rank(arr)

print(rank)



AttributeError: module 'numpy' has no attribute 'arrays'

In [40]:
#83. How to find the most frequent value in an array?

arr = np.array([1,2,3,2,2,3,4,4,5,6,6])

most_frequent_value = np.argmax(np.bincount(arr))

print(most_frequent_value)

2


In [42]:
#84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

matrix = np.random.randint(0,10,size=(10,10))

def extract_blocks(matrix):
    blocks = []
    rows,cols = matrix.shape

    for i in range(rows - 2):
        for j in range(cols -2):
            block = matrix[i:i+3, j:j+3]
            blocks.append(block)

    return blocks

extract_blocks(matrix)


[array([[9, 1, 7],
        [9, 7, 8],
        [7, 2, 8]], dtype=int32),
 array([[1, 7, 5],
        [7, 8, 3],
        [2, 8, 8]], dtype=int32),
 array([[7, 5, 8],
        [8, 3, 4],
        [8, 8, 6]], dtype=int32),
 array([[5, 8, 0],
        [3, 4, 3],
        [8, 6, 7]], dtype=int32),
 array([[8, 0, 5],
        [4, 3, 2],
        [6, 7, 4]], dtype=int32),
 array([[0, 5, 9],
        [3, 2, 3],
        [7, 4, 7]], dtype=int32),
 array([[5, 9, 2],
        [2, 3, 6],
        [4, 7, 0]], dtype=int32),
 array([[9, 2, 7],
        [3, 6, 4],
        [7, 0, 5]], dtype=int32),
 array([[9, 7, 8],
        [7, 2, 8],
        [5, 3, 8]], dtype=int32),
 array([[7, 8, 3],
        [2, 8, 8],
        [3, 8, 2]], dtype=int32),
 array([[8, 3, 4],
        [8, 8, 6],
        [8, 2, 7]], dtype=int32),
 array([[3, 4, 3],
        [8, 6, 7],
        [2, 7, 6]], dtype=int32),
 array([[4, 3, 2],
        [6, 7, 4],
        [7, 6, 6]], dtype=int32),
 array([[3, 2, 3],
        [7, 4, 7],
        [6, 6, 8]], dtype=

In [ ]:
#85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)
class SymmetricArray(np.ndarray):
    def __new__(cls, input_array):
        obj = np.asarray(input_array).view(cls)
        return obj

    def __array_finalize__(self, obj):
        if obj is None:
            return
        # Ensure the array is symmetric after any operations
        self[:] = (self + self.T) / 2

A=np.array([[1,2,3],
            [4,5,6],
            [3,4,5]])

S = SymmetricArray(A)

print(S)


: 

In [ ]:
#86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

p = 3
n = 4

matrices = np.random.rand(p,n,n)
vectors = np.random.rand(p,n,1)

sum_matrix= np.sum(np.matmul(matrices,vectors),axis =0)

print('Matrices:\n',matrices)
print('Vectors:\n',vectors)
print('Sum:\n',sum_matrix)

In [ ]:

#87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

arr = np.random.randint(1,10,size=(16,16))

blocks = arr.reshape(4,4,4,4)

blocks_sum = blocks.sum(axis=(-2,-1))

print('Original Array:\n',arr)
print('Block sum\n',blocks_sum)

In [ ]:
#88. How to implement the Game of Life using numpy arrays?

In [1]:
#89. How to get the n largest values of an array (★★★)

arr = np.array([3,1,5,6,3])

n = 3

largest_values = np.partition(arr, -n)[-n:]

print(largest_values)


NameError: name 'np' is not defined

In [ ]:

#90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)



In [ ]:
#91. How to create a record array from a regular array? (★★★)

regular_array = np.array([[1,'Kate',23],
                          [2,'James',24],
                          [3,'Jason',35]])

field_names = ['ID','Name','Age']

record_array = np.core.records.fromarrays(regular_array.T,names = fields)

print('Record Array:\n',record_array)

In [ ]:
#92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)
Z = np.random.rand(1000000)

Z_cubed = Z**3
Z_cubed = np.power(Z, 3)
Z_cubed = Z*Z*Z


In [ ]:
#93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [11,1,2],
              [3,5,6],
              [7,8,9],
              [2,4,6],
              [7,4,3]])

In [ ]:
#94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
#95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
#96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
#97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
#98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:

#99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
#100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)



